import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, LockKeyhole } from "lucide-react";
import { type FormEvent, useState } from "react";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { claimFirstAdmin } from "@/lib/catalog.functions";

const loginSchema = z.object({ email: z.string().trim().email("Enter a valid email address."), password: z.string().min(8, "Password must be at least 8 characters.") });

export const Route = createFileRoute("/admin/login")({
  head: () => ({ meta: [{ title: "Admin Login — Your Business" }, { name: "description", content: "Secure administrator access for Your Business." }, { property: "og:title", content: "Admin Login — Your Business" }, { property: "og:description", content: "Secure administrator access for Your Business." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }),
  component: AdminLogin,
});

function AdminLogin() {
  const navigate = useNavigate({ from: "/admin/login" });
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const [firstAdmin, setFirstAdmin] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); const parsed = loginSchema.safeParse({ email, password }); if (!parsed.success) { setError(parsed.error.issues[0]?.message ?? "Check your details."); return; } setBusy(true); if (firstAdmin) { const { data: signUpData, error: signUpError } = await supabase.auth.signUp(parsed.data); if (signUpError) setError(signUpError.message); else if (!signUpData.session) setError("Check your email to confirm the new administrator account, then sign in here."); else { await claimFirstAdmin(); await navigate({ to: "/admin" }); } setBusy(false); return; } const { data, error: signInError } = await supabase.auth.signInWithPassword(parsed.data); if (signInError || !data.user) { setError(signInError?.message || "Unable to sign in."); setBusy(false); return; } const { data: isAdmin } = await supabase.rpc("has_role", { _user_id: data.user.id, _role: "admin" }); if (!isAdmin) { await supabase.auth.signOut(); setError("This account does not have administrator access."); setBusy(false); return; } await navigate({ to: "/admin" }); };
  return <main className="grid min-h-screen bg-secondary/40 px-6 py-6 text-foreground lg:grid-cols-2 lg:px-10"><div className="flex flex-col"><Link to="/" className="flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={16} /> Back to website</Link><div className="my-auto max-w-md py-20"><div className="mb-10 grid h-12 w-12 place-items-center rounded-2xl bg-primary text-primary-foreground"><LockKeyhole size={21} /></div><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">Private area</p><h1 className="mt-4 font-display text-5xl font-semibold leading-none tracking-tight">{firstAdmin ? "Set up access." : "Welcome back."}</h1><p className="mt-5 leading-7 text-muted-foreground">{firstAdmin ? "Create the first administrator account for your workspace." : "Sign in to manage your collection and business details."}</p><form onSubmit={submit} className="mt-10 space-y-5"><label className="block text-sm font-semibold">Email<input value={email} onChange={(event) => setEmail(event.target.value)} type="email" autoComplete="email" className="mt-2 h-12 w-full rounded-xl border border-input bg-background px-4 font-normal outline-none ring-offset-background focus:ring-2 focus:ring-ring" /></label><label className="block text-sm font-semibold">Password<input value={password} onChange={(event) => setPassword(event.target.value)} type="password" autoComplete={firstAdmin ? "new-password" : "current-password"} className="mt-2 h-12 w-full rounded-xl border border-input bg-background px-4 font-normal outline-none ring-offset-background focus:ring-2 focus:ring-ring" /></label>{error && <p role="alert" className="text-sm font-medium text-destructive">{error}</p>}<Button type="submit" disabled={busy} className="w-full">{busy ? "Working…" : firstAdmin ? "Create administrator" : "Sign in"}</Button></form><button type="button" onClick={() => { setFirstAdmin(!firstAdmin); setError(""); }} className="mt-5 text-sm font-semibold text-muted-foreground underline-offset-4 hover:text-foreground hover:underline">{firstAdmin ? "Already have an account? Sign in" : "Set up the first administrator"}</button></div></div><div className="hidden items-end rounded-[2rem] bg-primary p-10 text-primary-foreground lg:flex"><div><p className="font-display text-4xl font-semibold leading-tight">A quieter way to keep everything current.</p><p className="mt-5 max-w-md text-primary-foreground/70">Update products, availability, featured items, and contact details from one place.</p></div></div></main>;
}