import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, Search } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { ProductCard } from "@/components/products/product-card";
import { supabase } from "@/integrations/supabase/client";
import { resolveProductImageUrls } from "@/lib/catalog.functions";
import type { BusinessSettings, Product } from "@/lib/catalog";

export const Route = createFileRoute("/products")({
  head: () => ({ meta: [{ title: "Collection — Your Business" }, { name: "description", content: "Browse the full Your Business product collection." }, { property: "og:title", content: "Collection — Your Business" }, { property: "og:description", content: "Browse the full Your Business product collection." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }),
  component: ProductsPage,
});

function ProductsPage() {
  const [products, setProducts] = useState<Product[]>([]); const [settings, setSettings] = useState<BusinessSettings | null>(null); const [imageUrls, setImageUrls] = useState<Record<string, string>>({}); const [category, setCategory] = useState("All"); const [search, setSearch] = useState("");
  const load = async () => { const [{ data }, { data: settingsData }] = await Promise.all([supabase.from("products").select("*").order("sort_order"), supabase.from("business_settings").select("*").eq("id", "default").maybeSingle()]); const next = data ?? []; setProducts(next); setSettings(settingsData); const paths = [...next.map((p) => p.image_url ?? ""), settingsData?.logo_url ?? ""].filter(Boolean); if (paths.length) setImageUrls(await resolveProductImageUrls({ data: { paths } })); };
  useEffect(() => { void load(); const channel = supabase.channel("products-page").on("postgres_changes", { event: "*", schema: "public", table: "products" }, load).on("postgres_changes", { event: "*", schema: "public", table: "business_settings" }, load).subscribe(); return () => { void supabase.removeChannel(channel); }; }, []);
  const categories = ["All", ...Array.from(new Set(products.map((p) => p.category)))]; const filtered = useMemo(() => products.filter((p) => (category === "All" || p.category === category) && `${p.name} ${p.description} ${p.category}`.toLowerCase().includes(search.toLowerCase())), [products, category, search]);
  return <main className="min-h-screen bg-background px-6 py-6 text-foreground lg:px-10"><div className="mx-auto max-w-7xl"><header className="flex items-center justify-between"><Link to="/" className="flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={16} /> Back home</Link><Link to="/" className="font-display text-xl font-semibold">{settings?.business_name || "Your Business"}</Link><span className="w-24" /></header><div className="py-20"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">The collection</p><h1 className="mt-4 max-w-3xl font-display text-6xl font-semibold leading-none tracking-tight sm:text-8xl">Find your next favorite.</h1><div className="mt-10 flex flex-col justify-between gap-4 border-b border-border pb-5 md:flex-row md:items-center"><div className="flex flex-wrap gap-2">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`rounded-full px-4 py-2 text-sm font-semibold transition-colors ${category === item ? "bg-primary text-primary-foreground" : "bg-secondary text-muted-foreground hover:text-foreground"}`}>{item}</button>)}</div><label className="flex items-center gap-2 border-b border-border px-1 py-2 text-sm text-muted-foreground"><Search size={16} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search collection" className="w-40 bg-transparent outline-none placeholder:text-muted-foreground" /></label></div><div className="mt-12 grid gap-x-6 gap-y-14 sm:grid-cols-2 lg:grid-cols-3">{filtered.map((product) => <ProductCard key={product.id} product={product} imageUrl={imageUrls[product.image_url ?? ""]} whatsappNumber={settings?.whatsapp_number ?? ""} />)}</div>{!filtered.length && <p className="py-20 text-center text-muted-foreground">No products match this search.</p>}</div></div></main>;
}