import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { formatPrice, placeholderImage, type BusinessSettings, type Product, whatsappHref } from "@/lib/catalog";
import { resolveProductImageUrls } from "@/lib/catalog.functions";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/products/$productId")({ head: () => ({ meta: [{ title: "Product — Your Business" }, { name: "description", content: "Explore a product from the Your Business collection." }, { property: "og:title", content: "Product — Your Business" }, { property: "og:description", content: "Explore a product from the Your Business collection." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: ProductDetails });
function ProductDetails() { const { productId } = Route.useParams(); const [product, setProduct] = useState<Product | null>(null); const [settings, setSettings] = useState<BusinessSettings | null>(null); const [imageUrl, setImageUrl] = useState(""); useEffect(() => { const load = async () => { const [{ data }, { data: settingsData }] = await Promise.all([supabase.from("products").select("*").eq("id", productId).maybeSingle(), supabase.from("business_settings").select("*").eq("id", "default").maybeSingle()]); setProduct(data); setSettings(settingsData); if (data?.image_url) { const urls = await resolveProductImageUrls({ data: { paths: [data.image_url] } }); setImageUrl(urls[data.image_url] ?? ""); } }; void load(); }, [productId]); if (!product) return <main className="grid min-h-screen place-items-center bg-background"><p className="text-muted-foreground">Product not found.</p></main>; return <main className="min-h-screen bg-background px-6 py-6 text-foreground lg:px-10"><div className="mx-auto max-w-7xl"><Link to="/products" className="inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={16} /> Back to collection</Link><div className="grid gap-12 py-16 lg:grid-cols-2 lg:items-center lg:py-24"><div className="aspect-[4/5] overflow-hidden rounded-[2rem] bg-muted"><img src={imageUrl || product.image_url || placeholderImage} alt={product.name} className="h-full w-full object-cover" /></div><div className="max-w-xl"><p className="text-xs font-semibold uppercase tracking-[0.25em] text-primary">{product.category}</p><h1 className="mt-5 font-display text-6xl font-semibold leading-none tracking-tight">{product.name}</h1><p className="mt-7 text-lg leading-8 text-muted-foreground">{product.description}</p><div className="mt-10 flex items-center gap-6"><span className="text-2xl font-semibold">{formatPrice(product.price)}</span><span className={product.available ? "text-sm font-semibold text-primary" : "text-sm font-semibold text-muted-foreground"}>{product.available ? "Available" : "Currently Unavailable"}</span></div><Button asChild size="lg" className="mt-10"><a href={whatsappHref(settings?.whatsapp_number ?? "", product.name)} target="_blank" rel="noreferrer">Ask about this product <ArrowUpRight size={17} /></a></Button></div></div></div></main>; }